
import { Language } from './types';

export const API_BASE_URL = 'http://localhost:5000/api';
export const CURRENT_FARMER_ID = 1;

export const APP_ROUTES = {
  HOME: '/',
  VOICE: '/voice',
  ACTIVITY: '/activity',
  FINANCE: '/finance',
  SCHEMES: '/schemes',
};

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    appName: "Krishi Sahayak",
    greeting: "Hello Farmer!",
    prompt: "What would you like to record today?",
    voiceBtn: "Record by Voice",
    voiceSub: "Seeds, Fertilizer, Water, Expense",
    diary: "Farm Diary",
    diarySub: "View past activities",
    finance: "Finance",
    financeSub: "Income & Expenses",
    schemes: "Schemes & Weather",
    schemesSub: "Govt Benefits",
    tabWeather: "Weather",
    tabSchemes: "Schemes",
    tabInsights: "AI Insights",
    navHome: "Home",
    navWork: "Work",
    navSpeak: "Speak",
    navMoney: "Money",
    navPlan: "Plan",
    listening: "Listening...",
    processing: "Processing...",
    speakNow: "Speak now",
    speakHint: "e.g., 'Sowed Tomato in 2 acres today'",
    speakHint2: "or: 'Bought fertilizer for 500 rupees'",
    micHint: "Tap mic to speak",
    stop: "Stop",
    success: "Success!",
    saved: "Information saved successfully.",
    retry: "Try Again",
    confirmTitle: "You said:",
    aiUnderstood: "AI Understood:",
    incorrect: "Incorrect",
    correct: "Confirm",
    weatherAlert: "Weather Alerts",
    fiveDayForecast: "5-Day Forecast",
    cropRec: "Crop Recommendation",
    govtSchemes: "Govt Schemes",
    income: "Income",
    expense: "Expense",
    netProfit: "Net Profit",
    totalIncome: "Total Income",
    totalExpense: "Total Expense",
    noAlerts: "No active alerts.",
    loading: "Loading...",
    noData: "No data found.",
    crop: "Crop",
    amount: "Amount",
    activity: "Activity",
    acres: "Acres",
    errorGeneric: "Something went wrong.",
    errorBrowser: "Your browser does not support voice.",
    suitabilityHigh: "Highly Suitable",
    suitabilityMed: "Moderately Suitable",
    suitabilityLow: "Low Suitability",
    currentLocation: "Location",
    aiProfitPrediction: "AI Profit Prediction",
    aiPredictionSub: "Next month's expected profit based on your patterns:",
    profitTrend: "Profit Trend",
    expenseDistribution: "Expense Distribution",
    weatherProfitInsight: "Weather-Profit Insight",
    weatherProfitSub: "Our analysis shows a positive correlation between rainfall and your farm's profit.",
    riskLevel: "Risk Level",
    riskLow: "Low Risk",
    riskMed: "Moderate Risk",
    riskHigh: "High Risk",
    potentialProfit: "Potential Profit",
    marketTrend: "Market Trend",
    riskRainfall: "Low Rainfall: Possible Water Stress",
    riskHumidity: "High Humidity: Pest Risk",
    riskMarket: "Price Volatility Expected",
    riskNone: "Stable Conditions",
    crop_Rice: "Rice",
    crop_Wheat: "Wheat",
    crop_Maize: "Maize",
    crop_Sugarcane: "Sugarcane",
    crop_Cotton: "Cotton",
    crop_Pulses: "Pulses"
  },
  [Language.HINDI]: {
    appName: "कृषि सहायक",
    greeting: "नमस्ते किसान भाई!",
    prompt: "आज आप क्या दर्ज करना चाहेंगे?",
    voiceBtn: "बोलकर दर्ज करें",
    voiceSub: "बीज, खाद, पानी, खर्चा",
    diary: "खेती डायरी",
    diarySub: "पिछले काम देखें",
    finance: "हिसाब किताब",
    financeSub: "खर्चा और मुनाफा",
    schemes: "योजना और मौसम",
    schemesSub: "सरकारी लाभ",
    tabWeather: "मौसम",
    tabSchemes: "योजनाएं",
    tabInsights: "AI अंतर्दृष्टि",
    navHome: "मुख्य",
    navWork: "कार्य",
    navSpeak: "बोलें",
    navMoney: "वित्त",
    navPlan: "योजना",
    listening: "सुन रहा हूँ...",
    processing: "समझ रहा हूँ...",
    speakNow: "बोलकर बताएं",
    speakHint: "जैसे: 'आज 2 एकड़ में टमाटर लगाए'",
    speakHint2: "या: '500 रुपये की खाद खरीदी'",
    micHint: "माइक दबाएं और बोलें",
    stop: "रुकें",
    success: "सफल!",
    saved: "जानकारी सुरक्षित कर ली गई है।",
    retry: "पुनः प्रयास करें",
    confirmTitle: "आपने कहा:",
    aiUnderstood: "AI ने समझा:",
    incorrect: "सुधारें",
    correct: "पुष्टि करें",
    weatherAlert: "मौसम चेतावनी",
    fiveDayForecast: "5-दिवसीय पूर्वानुमान",
    cropRec: "उपयुक्त फसलें",
    govtSchemes: "सरकारी योजनाएं",
    income: "आय",
    expense: "व्यय",
    netProfit: "कुल लाभ",
    totalIncome: "कुल आय",
    totalExpense: "कुल व्यय",
    noAlerts: "कोई चेतावनी नहीं।",
    loading: "प्रतीक्षा करें...",
    noData: "कोई जानकारी नहीं",
    crop: "फसल",
    amount: "धनराशि",
    activity: "गतिविधि",
    acres: "एकड़",
    errorGeneric: "त्रुटि हुई।",
    errorBrowser: "ब्राउज़र सपोर्ट नहीं करता।",
    suitabilityHigh: "अत्यधिक उपयुक्त",
    suitabilityMed: "मध्यम उपयुक्त",
    suitabilityLow: "कम उपयुक्त",
    currentLocation: "स्थान",
    aiProfitPrediction: "AI मुनाफा अनुमान",
    aiPredictionSub: "आपके खर्च के आधार पर अगले महीने का अपेक्षित लाभ:",
    riskLevel: "जोखिम स्तर",
    riskLow: "कम जोखिम",
    riskMed: "सामान्य जोखिम",
    riskHigh: "अधिक जोखिम",
    potentialProfit: "संभावित लाभ",
    marketTrend: "बाजार रुझान",
    riskRainfall: "कम वर्षा: पानी की कमी संभव",
    riskHumidity: "अधिक नमी: कीट का खतरा",
    riskMarket: "कीमतों में उतार-चढ़ाव",
    riskNone: "स्थिर स्थिति",
    crop_Rice: "चावल (धान)",
    crop_Wheat: "गेहूं",
    crop_Maize: "मक्का",
    crop_Sugarcane: "गन्ना",
    crop_Cotton: "कपास",
    crop_Pulses: "दालें"
  },
  [Language.MARATHI]: {
    appName: "कृषी सहाय्यक",
    greeting: "नमस्कार शेतकरी दादा!",
    prompt: "आज आपण काय नोंदवू इच्छिता?",
    voiceBtn: "बोलून नोंद करा",
    voiceSub: "बियाणे, खत, पाणी, खर्च",
    diary: "शेती डायरी",
    diarySub: "मागील कामे पहा",
    finance: "आर्थिक व्यवहार",
    financeSub: "खर्च आणि नफा",
    schemes: "योजना आणि हवामान",
    schemesSub: "सरकारी लाभ",
    tabWeather: "हवामान",
    tabSchemes: "योजना",
    tabInsights: "AI विश्लेषण",
    navHome: "मुख्य",
    navWork: "काम",
    navSpeak: "बोलून",
    navMoney: "हिशोब",
    navPlan: "नियोजन",
    listening: "ऐकत आहे...",
    processing: "विचार करत आहे...",
    speakNow: "बोला",
    speakHint: "उदा: 'आज २ एकरात टोमॅटो लावले'",
    speakHint2: "किंवा: '५०० रुपयांचे खत आणले'",
    micHint: "माईक दाबा आणि बोला",
    stop: "थांबा",
    success: "यशस्वी!",
    saved: "माहिती जतन केली आहे.",
    retry: "पुन्हा प्रयत्न करा",
    confirmTitle: "तुम्ही म्हणालात:",
    aiUnderstood: "AI ला समजले:",
    incorrect: "चूक आहे",
    correct: "बरोबर आहे",
    weatherAlert: "हवामान इशारे",
    fiveDayForecast: "५-दिवसीय हवामान",
    cropRec: "पिकांचा सल्ला",
    govtSchemes: "सरकारी योजना",
    income: "उत्पन्न",
    expense: "खर्च",
    netProfit: "निव्वळ नफा",
    totalIncome: "एकूण उत्पन्न",
    totalExpense: "एकूण खर्च",
    noAlerts: "कोणतेही इशारे नाहीत.",
    loading: "लोड होत आहे...",
    noData: "माहिती उपलब्ध नाही",
    crop: "पीक",
    amount: "रक्कम",
    activity: "काम",
    acres: "एकड",
    errorGeneric: "काहीतरी चूक झाली.",
    errorBrowser: "ब्राउझर सपोर्ट करत नाही.",
    riskLevel: "धोका पातळी",
    riskLow: "कमी धोका",
    riskMed: "मध्यम धोका",
    riskHigh: "जास्त धोका",
    potentialProfit: "संभाव्य नफा",
    marketTrend: "बाजार कल",
    riskRainfall: "कमी पाऊस: पाण्याची कमतरता",
    riskHumidity: "जास्त आर्द्रता: कीड लागण्याची शक्यता",
    riskMarket: "बाजारात चढ-उतार शक्यता",
    riskNone: "परिस्थिती स्थिर",
    crop_Rice: "तांदूळ (धान)",
    crop_Wheat: "गहू",
    crop_Maize: "मका",
    crop_Sugarcane: "ऊस",
    crop_Cotton: "कापूस",
    crop_Pulses: "डाळी"
  },
  [Language.GUJARATI]: {
    appName: "કૃષિ સહાયક",
    greeting: "નમસ્તે ખેડૂત મિત્ર!",
    prompt: "આજે તમે શું નોંધવા માંગો છો?",
    voiceBtn: "બોલીને નોંધ કરો",
    voiceSub: "બિયારણ, ખાતર, પાણી, ખર્ચ",
    diary: "ખેતી ડાયરી",
    diarySub: "જૂની પ્રવૃત્તિઓ જુઓ",
    finance: "હિસાબ કિતાબ",
    financeSub: "આવક અને ખર્ચ",
    schemes: "યોજના અને હવામાન",
    schemesSub: "સરકારી લાભો",
    tabWeather: "હવામાન",
    tabSchemes: "યોજનાઓ",
    tabInsights: "AI અનુમાન",
    navHome: "હોમ",
    navWork: "કામ",
    navSpeak: "બોલો",
    navMoney: "હિસાબ",
    navPlan: "યોજના",
    listening: "સાંભળી રહ્યા છીએ...",
    processing: "પ્રોસેસિંગ...",
    speakNow: "હમણાં બોલો",
    speakHint: "દા.ત., 'આજે 2 એકરમાં ટામેટા વાવ્યા'",
    speakHint2: "અથવા: '500 રૂપિયાનું ખાતર ખરીદ્યું'",
    micHint: "બોલવા માટે માઇક દબાવો",
    stop: "રોકો",
    success: "સફળ!",
    saved: "માહિતી સાચવવામાં આવી.",
    retry: "ફરી પ્રયાસ કરો",
    confirmTitle: "તમે કહ્યું:",
    aiUnderstood: "AI સમજ્યું:",
    incorrect: "ખોટું છે",
    correct: "સાચું છે",
    weatherAlert: "હવામાન ચેતવણી",
    fiveDayForecast: "5-દિવસની આગાહી",
    cropRec: "પાકની ભલામણ",
    govtSchemes: "સરકારી યોજનાઓ",
    income: "આવક",
    expense: "ખર્ચ",
    netProfit: "ચોખ્ખો નફો",
    totalIncome: "કુલ આવક",
    totalExpense: "કુલ ખર્ચ",
    noAlerts: "કોઈ ચેતવણી નથી.",
    loading: "લોડ થઈ રહ્યું છે...",
    noData: "માહિતી મળી નથી.",
    riskLevel: "જોખમનું સ્તર",
    riskLow: "ઓછું જોખમ",
    riskMed: "મધ્યમ જોખમ",
    riskHigh: "વધારે જોખમ",
    potentialProfit: "સંભવિત નફો",
    marketTrend: "બજારનું વલણ",
    riskRainfall: "ઓછો વરસાદ: પાણીની અછત શક્ય",
    riskHumidity: "વધારે ભેજ: જીવાતનો ભય",
    riskMarket: "ભાવમાં વધઘટની શક્યતા",
    riskNone: "પરિસ્થિતિ સ્થિર છે",
    crop_Rice: "ચોખા (ડાંગર)",
    crop_Wheat: "ઘઉં",
    crop_Maize: "મકાઈ",
    crop_Sugarcane: "શેરડી",
    crop_Cotton: "કપાસ",
    crop_Pulses: "કઠોળ"
  }
};
